spring:
  codec:
    max-in-memory-size: 10MB
  application:
    name: IBSApplication
  datasource:
    url: "URL"
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8082

security:
  user:
    password: password
  oauth2:
    resource:
      filter-order: 3



graphql-api: 
AWS_APPSYNC_API_KEY: 

jwt-secret: 
