import i18n from "i18next";
import { useTranslation, initReactI18next } from "react-i18next";

i18n.use(initReactI18next).init({
  resources: {
    en: {
      translation: {
        Search: "1. Search",
        "Choose Room": "2. Choose Room",
        "Choose Addon": "3. Choose Addon",
        Checkout: "4. Checkout",
        Guests: "Guests",
        Room: "Room",
        Beds: "Beds",
        Showing: "Showing",
        Property: "Property",
        checkinDate: "Check-in",
        checkoutDate: "Check-out",
        "Search Button": "Search",
        "Narrow your Result": "Narrow your Result",
        SUPER_DELUXE: "SUPER DELUXE",
        FAMILY_DELUXE: "FAMILY DELUXE",
        GRAND_DELUXE: "GRAND DELUXE",
        STANDARD_SUITE: "STANDARD SUITE",
        COUPLE_SUITE: "COUPLE SUITE",
        GARDEN_SUITE: "GARDEN SUITE",
        Inclusive: "Inclusive",
        Single: "Single",
        Double: "Double",
        Compare: "Compare",
        FilterRoomType: "Room Type",
        FilterBedType: "Bed Type",
        "per night": "per night ",
        "Select Room": "Select Room",
        Accessible: "I need an Accessible Room",
        Kids: "Kids",
        Adult: "Adult",
        Login: "LOGIN",
        BuildTrip: "BUILD A TRIP",
        MyTrips: "MY TRIPS",
        "Room Results": "Room Results",
        "Book Now": "Book Now",
        HotelName: "Team-1 Hotel",
        cur: "$",
        "The 29-story Super Delux rooms are smoke free and feature everyday comfort in jewel tones. The 351 sq.ft rooms, located near the pools and the Adventuredome, feature pillow-top mattresses, flat screen TV and Wi-Fi and internet access.":
          "The 29-story Super Delux rooms are smoke free and feature everyday comfort in jewel tones. The 351 sq.ft rooms, located near the pools and the Adventuredome, feature pillow-top mattresses, flat screen TV and Wi-Fi and internet access.",
      },
    },
    fr: {
      translation: {
        Search: "1. Rechercher",
        "Choose Room": "2. Choisissez la chambre",
        "Choose Addon": "3. Choisissez l'extension",
        Checkout: "4. Vérifier",
        Guests: "Invités",
        Room: "Salle",
        Beds: "Des lits",
        checkinDate: "Check-in",
        checkoutDate: "Check-out",
        Showing: "Montrant",
        "Search Button": "Rechercher",
        "Narrow your Result": "Affinez votre résultat",
        SUPER_DELUXE: "SUPER DE LUXE",
        FAMILY_DELUXE: "FAMILLE DE LUXE",
        GRAND_DELUXE: "GRANDE DELUXE",
        STANDARD_SUITE: "SUITE STANDARD",
        COUPLE_SUITE: "SUITE COUPLE",
        GARDEN_SUITE: "SUITE JARDIN",
        Inclusive: "Comprise",
        Single: "Seul",
        Double: "Double",
        Compare: "Comparer",
        FilterRoomType: "Type de chambre",
        FilterBedType: "Type de lit",
        "per night": "par nuit ",
        "Select Room": "Sélectionnez",
        Accessible: "J'ai besoin d'une chambre accessible",
        Kids: "Kids",
        Adult: "Adult",
        Property: "Biens",
        Login: "CONNEXION",
        BuildTrip: "CONSTRUIRE UN VOYAGE",
        MyTrips: "MES EXCURSIONS",
        "Room Results": "Résultats de la chambre",
        "Book Now": "Reserve maintenant",
        HotelName: "Équipe-1 Hôtel",
        cur: "€",
        "The 29-story Super Delux rooms are smoke free and feature everyday comfort in jewel tones. The 351 sq.ft rooms, located near the pools and the Adventuredome, feature pillow-top mattresses, flat screen TV and Wi-Fi and internet access.":
          "Les chambres Super Delux de 29 étages sont non-fumeurs et offrent un confort quotidien dans des tons de joyaux. Les chambres de 351 pieds carrés, situées près des piscines et de l'Adventuredome, disposent de matelas à plateau-coussin, d'une télévision à écran plat et d'un accès Wi-Fi et Internet.",
      },
    },
  },
  lng: "en",
  fallbackLng: "en",

  interpolation: {
    escapeValue: false,
  },
});
